version: '3'

services:

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command:
      - -c
      - max_prepared_transactions=100
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    hostname: rabbit1
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
      
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
